name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd chat-app
          git pull
          /home/rushi/.nvm/versions/node/v16.8.0/bin/pm2 restart client
          /home/rushi/.nvm/versions/node/v16.8.0/bin/pm2 restart server
    
